//STEP -2 Write Reducer function whicg update states based on action

import { Action } from '@ngrx/store';
import { UserActionTypes } from './user.actions';
import { usersData } from './user-list/user-list-item/uses.data';

//generated by scehamtics
export interface UserState {
    userCount : number;
    users : User[];
}

export const initialState: UserState = {userCount :0, users : undefined};

export function userReducer(state :UserState = initialState, action): UserState {
  switch (action.type) {

    case UserActionTypes.LoadAllUsers : return {userCount : action.payload.users.length, users : action.payload.users}

    case UserActionTypes.DeleteUser : return {userCount : action.payload.users.length, users : action.payload.users}

    default: return state;
  }
}